* updated to Nauty/Traces 2.5r2  * updated license.txt  * added gentourng to the list of binaries imported into Sage  * added src/ to .hgignore  * Added ">&2" to all echo in spkg-install

diff --git a/build/pkgs/nauty/spkg-install b/build/pkgs/nauty/spkg-install
--- a/build/pkgs/nauty/spkg-install
+++ b/build/pkgs/nauty/spkg-install
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
+   echo >&2 "SAGE_LOCAL undefined ... exiting";
+   echo >&2 "Maybe run 'sage -sh'?"
    exit 1
 fi
 
 cat license.txt
-echo "**************************************************"
-echo "NOTE that Nauty's License is NOT GPL-compatible"
-echo "**************************************************"
+echo >&2 "**************************************************"
+echo >&2 "NOTE that Nauty's License is NOT GPL-compatible"
+echo >&2 "**************************************************"
 
 cp patches/gtools-h.in src/
 
@@ -17,22 +17,22 @@ cd src
 
 ./configure --prefix="$SAGE_LOCAL"
 if [ $? -ne 0 ]; then
-   echo "Error configuring nauty."
+   echo >&2 "Error configuring nauty."
    exit 1
 fi
 
 make
 if [ $? -ne 0 ]; then
-   echo "Error building nauty."
+   echo >&2 "Error building nauty."
    exit 1
 fi
 
-echo "Copying nauty..."
-for program in addedgeg amtog biplabg catg complg copyg countg deledgeg directg dreadnaut dretog genbg geng genrang labelg listg multig newedgeg NRswitchg pickg planarg shortg showg;
+echo >&2 "Copying nauty..."
+for program in addedgeg amtog biplabg catg complg copyg countg deledgeg directg dreadnaut dretog genbg geng genrang labelg listg multig newedgeg NRswitchg pickg planarg shortg showg gentourng;
 do
   cp $program $SAGE_LOCAL/bin/nauty-$program
   if [ $? -ne 0 ]; then
-   echo "Error installing nauty."
+   echo >&2 "Error installing nauty."
    exit 1
   fi
 done
