Exit with a failure, if David Green's executables did not work correctly - This refers to a problem with higher optimization and older gcc versions

diff --git a/build/pkgs/p_group_cohomology/spkg-install b/build/pkgs/p_group_cohomology/spkg-install
--- a/build/pkgs/p_group_cohomology/spkg-install
+++ b/build/pkgs/p_group_cohomology/spkg-install
@@ -50,6 +50,10 @@ $MKDIR bin
 $MAKE
 if [ $? -ne 0 ]; then
    echo "Error building pGroupCohomology."
+   echo "You are using" $CC `$CC -dumpversion`
+   echo "If this is older than gcc 4.6, then please consider upgrading your system-wide gcc,"
+   echo "or install Sage with its gcc spkg."
+   echo "If your gcc version is more recent, then please inform the author."
    exit 1
 fi
 
@@ -60,6 +64,10 @@ if [ $? -ne 0 ]; then
 fi
 
 python setup.py install
+if [ $? -ne 0 ]; then
+   echo "Error installing Cython code."
+   exit 1
+fi
 
 # Perhaps we are supposed to build the docs?
 if [ "x$SAGE_SPKG_INSTALL_DOCS" = xyes ] ; then
